# service_b depends on service_a.

version: "3"

services:
  service_a:
    image: busybox
    # Use httpd just for preventing container from stopping.
    command: httpd -f
    healthcheck:
      test: exit 0
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
  service_b:
    image: busybox
    depends_on:
      service_a:
        condition: service_healthy
