# service_a ┐
#           ├ service_b ─┐
#           └ service_c ─┴ service_d

version: "3"

services:
  service_a:
    image: busybox
  service_b:
    image: busybox
    depends_on:
      - service_a
  service_c:
    image: busybox
    depends_on:
      - service_a
  service_d:
    image: busybox
    depends_on:
      - service_b
      - service_c
